Usuarios
DeustoPWEB2018/Elementos-de-la-UX pull request #11
Opened 2018-10-04 11:00 UTC by Marinaperezmaza

2018-10-05 08:53 UTC, mberasategi commented
Kaixo @Marinaperezmaza , tienes que establecer como **Reviewers** a las personas que han trabajado contigo en el grupo de expertos, no a mí.

2018-10-05 09:07 UTC, mirenbz reviewed
Por otra parte, y como se especifica en [el punto 4 de las tareas específicas para Control](https://github.com/DeustoPWEB2018/Elementos-de-la-UX/blob/master/instrucciones.md#control), tienes que renombrar el archivo que has creado como `Cómo conocer las necesiades de tus usuarios` a algo que no tenga espacios, ni tildes, ni preferentemente mayúsculas, y que termine en `.md`. Para esto,

- desde la terminal, `git pull origin usuarios`
- abre el archivo en Sublime Text, y haz `File > Save as`, y dale el nombre correcto (por ejemplo, `como-conocer-necesidades-usuarios.md`)
- desde tu explorador de archivos, borra el archivo `Cómo conocer las necesiades de tus usuarios`
- desde la terminal, 
    ```
    git add .
    git commit -m "Renombrar el archivo correctamente"
    git push origin usuarios
    ```

2018-10-08 08:06 UTC, mberasategi commented
Tenéis que renombrar el archivo como os indicaba en [el comentario anterior](https://github.com/DeustoPWEB2018/Elementos-de-la-UX/pull/11#pullrequestreview-161948599). Poneos de acuerdo para que lo haga una sola persona, y después, cuando esté hecho, las demás tendréis que hacer `git pull origin usuarios` desde vuestros ordenadores.

2018-10-08 14:01 UTC, Marinaperezmaza commented
Terminado

2018-10-08 14:53 UTC, mirenbz requested changes
Hacen falta algunos cambios para poder combinar este pull request. El primero, eliminar el archivo `Usuarios.md` de Angie, que ya está incorporado en el documento principal. Después, revisad la ortografía, quedan algunas erratas por corregir. Los demás están detallados sobre el mismo contenido.

2018-10-08 14:53 UTC, mberasategi commented on como-conocer-necesidades-usuarios.md
> +CÓMO CONOCER LAS NECESIDADES DE TUS USUARIOS
Os falta utilizar la sintaxis de Markdown para estructurar el documento. Así, este título principal del documento debería ser:

```
#  Cómo conocer las necesidades de tus usuarios
```

2018-10-08 14:53 UTC, mberasategi commented on como-conocer-necesidades-usuarios.md
> +INTRODUCCIÓN
En la misma línea, esto (y los equivalentes más adelante en el documento), que es un título de segundo nivel (_debajo_ del título principal del documento), sería:

```
## Introducción
```

2018-10-08 14:53 UTC, mberasategi commented on como-conocer-necesidades-usuarios.md
> +TIPOS DE TÉCNICAS
```
## Tipos de técnicas
```

2018-10-08 14:53 UTC, mberasategi commented on como-conocer-necesidades-usuarios.md
> +Skype como herramienta(ANGIE)
Título de tercer nivel, _debajo_ de "Tipos de técnicas".

```
### Skype como herramienta
```

2018-10-08 14:53 UTC, mberasategi commented on como-conocer-necesidades-usuarios.md
> +Skype como herramienta(ANGIE)
La persona asignada a cada sección es una información útil mientras trabajáis, pero no debería incluirse para la versión final.

2018-10-08 14:53 UTC, mberasategi commented on como-conocer-necesidades-usuarios.md
> +Si lo que necesitas es abarcar mucha audiencia por bajos costes Skype puede ser la solución. Puesto que para conocer a los usuarios es necesario comunicarse con ellos y esto se logra mediante la inte
Esta referencia a una fuente no está realizada de manera correcta. Revisad las [indicaciones de Verbum para las citas y bibliografía](http://verbum.idiomas.deusto.es/documentacion-citas-y-bibliografia/).

2018-10-08 15:32 UTC, mberasategi commented
Cuando acabéis con los cambios, @angielozanogr y @anejuaristi tienen que aprobarlos otra vez.

2018-10-08 15:41 UTC, anejuaristi reviewed
Correción ortográfica hecha

2018-10-08 15:42 UTC, anejuaristi requested changes
Correción ortográfica hecha

2018-10-08 15:44 UTC, anejuaristi submitted a review, later dismissed

2018-10-08 16:10 UTC, mirenbz approved these changes

2018-10-08 16:12 UTC, merged

2018-10-09 09:15 UTC, mberasategi commented
@anejuaristi @Marinaperezmaza y @angielozanogr , no olvidéis eliminar el branch de trabajo.

1. Alguien debe hacer clic en el botón **Delete branch** aquí abajo
2. En el ordenador de cada una, acceded a la carpeta `Elementos-de-la-UX` y:
    ```
    git checkout master
    git branch -d usuarios
    ```
3. Para terminar, actualizad vuestra copia local con los cambios de este repositorio:
    ```
    git pull origin master
    ```