Personasux
DeustoPWEB2018/Elementos-de-la-UX pull request #13
Opened 2018-10-05 09:54 UTC by mikelaranzabe

2018-10-05 13:19 UTC, mberasategi commented
¡Bien! :clap:

Ahora tenéis que añadir el contenido del acta al documento `personasux.md` (creo que es tarea de @estelleroques). Después, `git pull origin personasux` en vuestro ordenador (para obtener los cambios de Estelle), redactar cada uno lo suyo, y como siempre:

```
git add .
git commit -m "Mensaje sobre vuestros cambios"
git push origin personasux
```

2018-10-07 19:58 UTC, estelleroques submitted a review, later dismissed

2018-10-07 20:03 UTC, estelleroques commented
Hola @mberasategi!

No sé porque, no puedo anadir Mikel como "Reviewer"

Gracias!

2018-10-08 08:18 UTC, mberasategi commented
Hola @estelleroques , no puedes añadir a Mikel como reviewer porque él es quien creó el pull request. No es problema, continuad así. 

Cuando lo tengáis terminado, acordáos de [revisar y aprobar el contenido](https://github.com/DeustoPWEB2018/Elementos-de-la-UX/blob/master/instrucciones.md#revisar-y-aprobar-el-contenido) y de [marcarlo como finalizado](https://github.com/DeustoPWEB2018/Elementos-de-la-UX/blob/master/instrucciones.md#comunicaci%C3%B3n).

2018-10-08 09:11 UTC, estelleroques submitted a review, later dismissed

2018-10-08 10:42 UTC, estelleroques submitted a review, later dismissed

2018-10-08 14:42 UTC, mberasategi commented
@jcantero7 y @estelleroques, tenéis que aprobar las modificaciones para poder avanzar. Para esto:

- haced clic en la pestaña **Files changed** de arriba
- revisad ahí el contenido del documento `personasux.md`
- clic en el botón verde de la parte derecha en esa página, **Review changes** 
- si no hay que hacer ningún cambio más, seleccionad la opción **Approve** y clic en **Submit review**

2018-10-08 15:30 UTC, mirenbz requested changes
Tenéis algunas faltas de ortografía que habría que revisar. Se echa en falta algún modelo de ficha de persona. Tened en cuenta que vuestros compañeros NO han leído el texto en el que habéis basado vuestro texto, y por tanto no han tenido ocasión de ver cómo es un personaje. Si no recuerdo mal, hablamos en clase acerca de diferentes modelos que podían utilizarse.

2018-10-08 15:30 UTC, mberasategi commented on 1-estrategia/personasux.md
> +Lo primero que se tuvo que realizar fue una profunda investigación y para ello entrevistaron a la plantilla de Sony, de esta forma lograrían saber con gran precisión que quería lograr Sony TransCom c
Aquí (y en los demás párrafos de este apartado) tenéis que añadir una línea más (son dos saltos de línea) para indicar un párrafo.

2018-10-08 18:58 UTC, estelleroques approved these changes

2018-10-09 07:07 UTC, mirenbz approved these changes

2018-10-09 09:06 UTC, merged

2018-10-09 09:07 UTC, mberasategi commented
Falta la aprobación de @jcantero7 , pero he combinado el contenido de todas formas. Jon, recuerda hacerlo la próxima vez.