Canvas
DeustoPWEB2018/Elementos-de-la-UX pull request #14
Opened 2018-10-05 19:23 UTC by LisandroToledo

@mberasategi  como agrego a Leire sino aparece su usuario @leireneira para sumarla como "Reviewers"??

2018-10-05 22:00 UTC, LisandroToledo commented
> @mberasategi como agrego a Leire sino aparece su usuario @leireneira para sumarla como "Reviewers"??

Ya está solucionado... 👍

2018-10-06 16:31 UTC, leireneira submitted a review, later dismissed

2018-10-08 15:04 UTC, mberasategi commented
Hola @leireneira y @LisandroToledo , ¿está terminado vuestro contenido? Lo pregunto porque os habéis quedado bastante cortos de extensión. Por otro lado, si está terminado, hace falta que Leire apruebe los cambios. Para esto:

- haz clic en la pestaña **Files changed** de arriba
- revisa ahí el contenido del documento `canvas.md`
- clic en el botón verde de la parte derecha en esa página, **Review changes** 
- si no hay que hacer ningún cambio más, seleccionad la opción **Approve** y clic en **Submit review**

2018-10-09 10:54 UTC, leireneira submitted a review, later dismissed

2018-10-09 11:13 UTC, mirenbz requested changes
Tenéis que hacer algunos cambios para poder integrar este contenido.

1. Eliminar el archivo `Lean UX Canvas`
2. Revisar la ortografía
3. Realizar los cambios solicitados abajo ⬇️

2018-10-09 11:13 UTC, mberasategi commented on 1-estrategia/canvas.md
> +Unidad 1: Estrategia
Esta línea no hace falta. Eliminadla, por favor.

2018-10-09 11:13 UTC, mberasategi commented on 1-estrategia/canvas.md
> +## **Tema: Lean UX canvas**<h1>
Éste sería el título del documento, de primer nivel, por tanto:
```
# Lean UX Canvas
``` 

Sin el `<h1>` al final. Eso es HTML, y para estos documentos usaremos la sintaxis de Markdown.

2018-10-09 11:13 UTC, mberasategi commented on 1-estrategia/canvas.md
> +### Que es Lean UX canvas?<h2>
Éste título, por tanto, sería de segundo nivel, en lugar de tercero:
```
## ¿Qué es Lean UX canvas?
```

Tendréis que revisar también los siguientes títulos.

2018-10-09 11:13 UTC, mberasategi commented on 1-estrategia/canvas.md
> +A diferencia de los metodos tradicionales, donde el proceso sigue una lógica de "cascada", esta herramienta funciona con una mirada interactiva, circular y global, a través de un desarrollo ágil que
Hay que separar los párrafos con una línea en blanco (presionar `Enter` **dos** veces).

2018-10-09 11:13 UTC, mberasategi commented on 1-estrategia/canvas.md
> +~~~
Esta línea, al igual que la de más abajo, están de sobra.

2018-10-09 11:13 UTC, mberasategi commented on 1-estrategia/canvas.md
> +2. Resultados: Aquí habrá que poner cuales han sido los cambios que se han dado en el comportamiento de los usuarios/clientes que indicarán la resolución del problema. Normalmente, los miembros del g
> cuáles _**serán**_ los cambios que _**se puedan dar**_ en el comportamiento de los usuarios/clientes que indicarán la resolución del problema.

Es decir, ¿qué cambios querríamos ver en el comportamiento de los usuarios, para asumir que hemos resuelto el problema?

2018-10-09 11:13 UTC, mberasategi commented on 1-estrategia/canvas.md
> +###**Metodología**<h3>
Entiendo que este apartado debería ir más arriba en el documento, no después de las conclusiones.

2018-10-09 17:34 UTC, leireneira submitted a review, later dismissed

2018-10-09 18:25 UTC, leireneira submitted a review, later dismissed

2018-10-10 07:27 UTC, mirenbz commented
He tenido que realizar yo los cambios necesarios porque estamos totalmente fuera de plazo. Apruebo y combino con el branch `master`.

2018-10-10 07:27 UTC, mirenbz approved these changes

2018-10-10 08:09 UTC, merged