Añadir esquema tipografia
DeustoPWEB2018/Elementos-de-la-UX pull request #30
Opened 2018-11-28 16:02 UTC by mikelaranzabe

2018-11-30 11:17 UTC, meganeba submitted a review, later dismissed

2018-12-01 00:24 UTC, meganeba commented
@jcantero7 @mikelaranzabe No tenemos los acentos en mi ordenador, puedes revisar mi parte por favor? Y borrar mi nombre al lado del titulo en el mismo tiempo? Muchas gracias chicos :)

2018-12-03 09:52 UTC, mberasategi commented
Cuando tengáis el contenido listo, @meganeba y @jcantero7 , tenéis que seleccionar "Approve" en la pestaña de revisión de código para poder hacer merge.

2018-12-03 10:16 UTC, mirenbz approved these changes

2018-12-03 10:17 UTC, mirenbz requested changes
Os falta añadir las referencias.

2018-12-03 10:51 UTC, mirenbz approved these changes

2018-12-03 11:13 UTC, meganeba approved these changes

2018-12-03 11:39 UTC, merged